service: orgchart-ml-2

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  environment:
    SENTRY_DSN: ${env:SENTRY_DSN}
    CLIENT_ID: ${env:CLIENT_ID}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    SERVICE_DOMAIN: ${env:SERVICE_DOMAIN}
    MEDIA_DOMAIN: ${env:MEDIA_DOMAIN}
    CACHE_BUCKET: ${env:CACHE_BUCKET}
  region: eu-central-1
  memorySize: 1024
  timeout: 300
  iam:
    role: arn:aws:iam::889551677573:role/ml_beta_strukturen_bund_dev_lambda_role
  stage: ${opt:stage, "dev"}
  ecr:
    images:
      baseimage:
        path: ./

plugins:
  - serverless-domain-manager
functions:
  app:
    image: baseimage
    events:
      - http:
          method: any
          path: /{proxy+}
      - sns:
          arn: arn:aws:sns:eu-central-1:889551677573:orgchart-image-generator-ml-bund-dev
      - sns:
          arn: arn:aws:sns:eu-central-1:889551677573:orgchart-parser-ml-bund-dev
      - sns:
          topicName: orgchart-ml-test-topic

custom:
  customDomain:
    autoDomain: true
    domainName: ml.beta.strukturen.bund.dev
    endpointType: 'regional'
    securityPolicy: tls_1_2
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true