service: orgchart-ml

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: ${self:provider.stage}-layerName
      description: stuff
      compatibleRuntimes:
        - python3.8


functions:
  app:
    package:
      include:
        - "*.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - "node_modules/"

    handler: lambda.handler
    timeout: 120
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}