service: orgchart-ml

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "dev"}
  ecr:
    images:
      saveImage:
        path: ./

functions:
  app:
    package:
      include:
        - "*.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
        - "node_modules/"

    handler: lambda.handler
    timeout: 120
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}