service: orgchart-ml-2

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  ecr:
    images:
      baseimage:
        path: ./

functions:
  app:
    image: baseimage
    events:
      - http:
          method: any
          path: /{proxy+}