service: orgchart-ml

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerless: true
    slim: true
    zip: true

functions:
  app:
    package:
      include:
        - "*.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: lambda.handler
    timeout: 120
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /{proxy+}